name = "CVO Everything Compats"
prefix = "cvo_compats"
mainprefix = "z"

[properties]
author = "24th Chorni Voron"
url = "https://github.com/SkippieDippie/CVO-Everything-Compats"

[files]
include = [
    "mod.cpp",
    "meta.cpp",
    "LICENSE",
    "logo_ca.paa",
    "logo_co.paa"
]
exclude  = [
]
