name = "24th CVO Compatibilities"
prefix = "cvo_compats"
mainprefix = "z"

[properties]
author = "24th Chorni Voron"
url = "https://github.com/SkippieDippie/24th-CVO-Compatibilities"

[files]
include = [
    "mod.cpp",
    "meta.cpp",
    "LICENSE",
    "*.paa"
]
exclude  = [
]
