name: Validate

on:
  push:
    branches:
    - main
  pull_request:


jobs:
  check:
    runs-on: ubuntu-latest
    steps:
        - name: Checkout the source code
          uses: actions/checkout@v4
        
        - name: Validate Config
          run: python3 tools/config_style_checker.py
        
        - name: Check strings
          run: python3 tools/check_strings.py
        
        - name: Validate stringtables
          run: python3 tools/stringtable_validator.py
        
        - name: Setup HEMTT
          uses: arma-actions/hemtt@v1

        - name: Check with HEMTT
          run: hemtt check -p
